name: readventure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  d_chart: ^2.10.2 #세로 막대그래프 차트

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

  # 상태관리
  #  get: ^4.6.6 # getX, 상태 관리 플러그인
  #  provider: ^6.1.2 # provider, 상태 관리 플러그인
  flutter_riverpod: ^2.6.1 # riverpod, 상태 관리 플러그인 / provider의 상위버전
  lottie: ^3.1.3 # lottie, Lottie 파일 사용 플러그인

  flutter_screenutil: ^5.9.3 # screenutil, 화면에 따라 크기 조정
  easy_localization: ^3.0.7 # localization 사용 쉽게
  flutter_dotenv: ^5.2.1 # 환경 변수 처리
  http: ^1.2.1
  dart_openai: ^5.1.0
  permission_handler: ^11.1.0 # 권한 처리
  flutter_local_notifications: ^18.0.1  # local 알림 설정
  flutter_svg: ^2.0.16 # svg 파일 사용 위함


  # Firebase
  firebase_ui_auth: ^1.14.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.3

  # KaKaoTalk Login
  kakao_flutter_sdk_user: ^1.9.5
#  kakao_flutter_sdk: ^1.9.6

  # Google Sign In
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  change_app_package_name: ^1.4.0

# 앱 아이콘 변경 (사용 모르겟어)
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: "AppIcon"
#  image_path_ios: "assets/images/icon.png"
#  image_path_android: "assets/images/round-icon.png"
#  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  assets:
    - lib/localization/l10n/ko.json
    - lib/localization/l10n/en.json
    - .env
    - assets/images/
    - assets/lottie/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
