// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxLCd3CWWLgU32pcwTvOKpDZPwA9PVen8',
    appId: '1:194910563832:web:716469d5001f73d4c5fa0d',
    messagingSenderId: '194910563832',
    projectId: 'glang-98622',
    authDomain: 'glang-98622.firebaseapp.com',
    storageBucket: 'glang-98622.firebasestorage.app',
    measurementId: 'G-2CKZ7NSNCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HC3E_yewyCSEel9WIw16RsG8eAR9Nc8',
    appId: '1:194910563832:android:42afafeded30a1fbc5fa0d',
    messagingSenderId: '194910563832',
    projectId: 'glang-98622',
    storageBucket: 'glang-98622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHY6zKwK70eyWNIMh9Db11QWMJDv5qv5I',
    appId: '1:194910563832:ios:fe382d0bb5489e10c5fa0d',
    messagingSenderId: '194910563832',
    projectId: 'glang-98622',
    storageBucket: 'glang-98622.firebasestorage.app',
    androidClientId: '194910563832-23ei1u336vjar7j0p1fcb99oii3kqnnr.apps.googleusercontent.com',
    iosClientId: '194910563832-81q7mf4c284fcqn2q21rukie7qbq5oba.apps.googleusercontent.com',
    iosBundleId: 'com.zero.glang2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHY6zKwK70eyWNIMh9Db11QWMJDv5qv5I',
    appId: '1:194910563832:ios:86359fe9f0d2daa0c5fa0d',
    messagingSenderId: '194910563832',
    projectId: 'glang-98622',
    storageBucket: 'glang-98622.firebasestorage.app',
    iosClientId: '194910563832-l41ru5t3vakp4c9fpkk6u40pg7vh5uat.apps.googleusercontent.com',
    iosBundleId: 'com.zero.glang2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxLCd3CWWLgU32pcwTvOKpDZPwA9PVen8',
    appId: '1:194910563832:web:becc5f13082af544c5fa0d',
    messagingSenderId: '194910563832',
    projectId: 'glang-98622',
    authDomain: 'glang-98622.firebaseapp.com',
    storageBucket: 'glang-98622.firebasestorage.app',
    measurementId: 'G-MN60G45PYP',
  );
}